# TimedRewards by ImABradley
# Spigot: https://www.spigotmc.org/members/imabradley.292138/
#
# Plugin Version: 0.1
# MySQL support should hopefully be in 0.2.


# Sends anonymous information to mcstats.org. This allows me to see how many servers are using my plugin. (That's all!)
metrics-enabled: true

menus:
  rewards:
    # Size of the menu (inventory)
    # 56 = Double Chest | 28 = Single Chest
    size: 56

    # The name of the rewards menu.
    title: '&aRewards Menu'

    # This will replace all other items in the menu with the below id, 0 being air (nothing).
    other-items: 0

    reward-items:
      daily:
        # The id of the item to be shown.
        id: 265
        # The amount of blocks to be shown.
        amount: 1
        # Title of the item.
        name: '&cDaily Reward'
        # Time in seconds until they can claim it again.
        time: 86400
        # The lore of the item, a description if you like. Note put "lore: []", without quotation, if you don't want a lore.
        lore:
          - '&fYou can claim this reward once a day!'
          - '&fTime until next collection: &a{TIME}&f.'
        # The menu slot which the item will be displayed in.
        slot: 20
        # Commands which are ran when a player successfully claims a reward. (Messages are already sent, see messages.yml to change them)
        claim-rewards:
          - 'eco give {PLAYER} 1000'
      weekly:
        id: 266
        amount: 1
        name: '&cWeekly Reward'
        time: 604800
        lore:
          - '&fYou can claim this reward once a week!'
          - '&fTime until next collection: &a{TIME}&f.'
        slot: 21
        claim-rewards:
          - 'eco give {PLAYER} 5000'
      monthly:
        id: 264
        amount: 1
        name: '&cWeekly Reward'
        time: 604800
        lore:
          - '&fYou can claim this reward once a week!'
          - '&fTime until next collection: &a{TIME}&f.'
        slot: 22
        # You can make this permission whatever you want! This will prevent players without the permission claiming the reward.
        permission: timedrewards.monthly
        claim-rewards:
          - 'eco give {PLAYER} 10000'
  player: [] # TODO