# TimedRewards by ImABradley
# Spigot: https://www.spigotmc.org/members/imabradley.292138/
#
# config.yml
# Plugin Version: 0.1
# MySQL support will hopefully be in 0.2.


# Sends anonymous information to mcstats.org. This allows me to see how many servers are using my plugin. (That's all!)
metrics-enabled: true


# When right-clicking on an NPC this will open the rewards menu.(Works well with plugins such as Citizens).
npc-names:
  - '&a&lCarl the Creeper'
  - '&bThe Delivery Man'

# Allows the player to claim all rewards (if has permission) when their data is first created.
first-time-claim: true

# If true when a player attempts to claim (clicks) a reward the inventory will close, otherwise it will remain open.
close-inventory-on-claim: true

menus:
  rewards:
    # Size of the menu (inventory)
    # 54 = Double Chest | 27 = Single Chest
    size: 54

    # The name of the rewards menu.
    title: '&aRewards Menu'

    # This will replace all other items in the menu with the below id, 0 being air (nothing).
    # Note: If the item id has data make sure to put it as a string by surrounding it with quotes.
    #       Example: other-items: '160:15'
    other-items: 0

    reward-items:
      daily:
        # The id of the item to be shown.
        id: 265
        # The amount of blocks to be shown.
        amount: 1
        # Title of the item.
        name: '&cDaily Reward'
        # Time in seconds until they can claim it again.
        time: 86400
        # The lore of the item, a description if you like. Note put "lore: []", without quotation, if you don't want a lore.
        # Note: Using {time} will change to the 'claim-message' in messages.yml if there are 0s remaining. (recommended).
        # {time} - Example: 5d 01:01:42 (Same as: {days}d {hours}:{minutes}:{seconds})
        # {days}
        # {hours}
        # {minutes}
        # {seconds}
        lore:
          - '&fYou can claim this reward once a day!'
          - '&fTime until next collection: &a{time}&f.'
        # The menu slot which the item will be displayed in.
        slot: 21
        # Commands which are ran when a player successfully claims a reward. Note: Commands are ran as console.
        # {player} - The player's name.
        # {uuid}   - The player's uuid.
        claim-reward-cmds:
          - 'eco give {player} 1000'
          - 'tr msg {player} &7[&6TimedRewards&7] You have claimed the daily reward!'
      weekly:
        id: 266
        amount: 1
        name: '&cWeekly Reward'
        time: 604800
        lore:
          - '&fYou can claim this reward once a week!'
          - '&fTime until next collection: &a{time}&f.'
        slot: 22
        claim-reward-cmds:
          - 'eco give {player} 5000'
          - 'tr msg {player} &7[&6TimedRewards&7] You have claimed the weekly reward!'
      monthly:
        id: 264
        amount: 1
        name: '&cMonthly Reward'
        time: 2419200
        lore:
          - '&fYou can claim this reward once a month!'
          - '&fTime until next collection: &a{time}&f.'
        slot: 23
        # You can make this permission whatever you want! This will prevent players without the permission claiming the reward.
        permission: 'timedrewards.monthly'
        claim-reward-cmds:
          - 'eco give {player} 10000'
          - 'tr msg {player} &7[&6TimedRewards&7] You have claimed the monthly reward!'